namespace: fredericpetit-gh
name: graylog-minimal-install-containerized
version: 1.0.3
readme: README.md
authors:
  - "Frédéric Petit @fredericpetit-gh"
description: "Ansible role for deploying Graylog with MongoDB and OpenSearch, containerized with minimal installation."
license: MIT
dependencies: {}
tags:
  - graylog
  - docker
  - mongodb
  - opensearch
  - logging
  - minimal