- name: Create the net-log network with fixed subnet (Docker)
  docker_network:
    name: net-log
    driver: bridge
    state: present
    ipam_config:
      - subnet: "10.0.0.0/29"
        gateway: "10.0.0.1"
  when: container_driver == "docker"

- name: Create the net-log network with fixed subnet (Podman)
  containers.podman.podman_network:
    name: net-log
    state: present
    ipv4_subnet: "10.0.0.0/29"
    ipv4_gateway: "10.0.0.1"
  when: container_driver == "podman"

- name: Démarrer MongoDB
  include_tasks: mongo.yml

- name: Démarrer OpenSearch
  include_tasks: opensearch.yml

- name: Démarrer Graylog
  include_tasks: graylog.yml