# Docker
- name: Launch MongoDB container (Docker)
  docker_container:
    name: "{{ mongo_container_name }}"
    image: "{{ mongo_image }}"
    state: started
    restart_policy: unless-stopped
    networks:
      - name: net-log
  when: container_driver == "docker"

# Podman
- name: Launch MongoDB container (Podman)
  containers.podman.podman_container:
    name: "{{ mongo_container_name }}"
    image: "{{ mongo_image }}"
    state: started
    restart_policy: unless-stopped
    network: net-log
  when: container_driver == "podman"