- name: Lancer OpenSearch container
  docker_container:
    name: "{{ opensearch_container_name }}"
    image: "{{ opensearch_image }}"
    env:
      discovery.type: "single-node"
      plugins.security.disabled: "true"
    state: started
    restart_policy: unless-stopped