- name: Lancer OpenSearch container
  docker_container:
    name: "{{ opensearch_container_name }}"
    image: "{{ opensearch_image }}"
    ulimits:
      - name: "nofile"
        soft: 65536
        hard: 65536
    env:
      discovery.type: "single-node"
      plugins.security.disabled: "true"
    state: started
    restart_policy: unless-stopped